name: Build, Lint and Test
on: push

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  build:
    name: Build DEB/RPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nfpm@latest
        run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/nfpm.sh | sudo sh
      - name: Build packages
        run: make all
        env:
          NFPM: ./bin/nfpm
      - name: Upload .deb
        uses: actions/upload-artifact@v2
        with:
          name: portmaster.deb
          path: dist/portmaster_*.deb
      - name: Upload .rpm
        uses: actions/upload-artifact@v2
        with:
          name: portmaster.rpm
          path: dist/portmaster-*.rpm

  test-deb:
    name: Test DEB package (ubuntu VM)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: portmaster.deb

      - name: Install dependencies
        run: sudo bash -c "apt-get update && apt-get install -y libnetfilter-queue1"

      - name: Install deb package
        run: yes | sudo dpkg -i ./portmaster_*.deb

  test-rpm:
    name: Test RPM package
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        container:
          - fedora:32
          - fedora:33
          - fedora:34
          - centos:7
          - centos:8
          - opensuse/tumbleweed:latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: portmaster.rpm
      # we use yum localinstall instead of dnf install because
      # not all tested distro versions have dnf available and dnf
      # supports being aliased as yum
      - name: Install package
        run: yes | yum localinstall ./portmaster-*.rpm
